# Generated by Django 5.0.6 on 2024-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Названия задания')),
                ('is_complite', models.BooleanField(default=False, verbose_name='Завершенно')),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задание',
            },
        ),
    ]
